# Generated by Django 4.0.4 on 2022-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_presentation_measure_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicatioInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
