# Generated by Django 4.0.4 on 2022-09-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicatioinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicatioInventory',
        ),
    ]
