# Generated by Django 4.0.4 on 2022-10-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_user_first_name_alter_user_identification_type'),
        ('medications', '0004_delete_medicatioinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='apellidos')),
                ('identification_type', models.SmallIntegerField(blank=True, choices=[(1, 'C.C.'), (2, 'C.E.'), (3, 'Pasaporte'), (4, 'NUIP')], null=True, verbose_name='tipo de documento')),
                ('identification_number', models.CharField(blank=True, max_length=32, verbose_name='número de documento')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'No definido')], default=3, verbose_name='género')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('date_joined', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de ingreso')),
                ('eps', models.CharField(blank=True, max_length=128, verbose_name='EPS')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='apellidos')),
                ('identification_type', models.SmallIntegerField(blank=True, choices=[(1, 'C.C.'), (2, 'C.E.'), (3, 'Pasaporte'), (4, 'NUIP')], null=True, verbose_name='tipo de documento')),
                ('identification_number', models.CharField(blank=True, max_length=32, verbose_name='número de documento')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'No definido')], default=3, verbose_name='género')),
                ('kinship', models.SmallIntegerField(choices=[(1, 'Cónyuge'), (2, 'Padre / Madre'), (3, 'Hermano / Hermana'), (4, 'Hijo / Hija'), (5, 'Abuelo / Abuela'), (6, 'Familiar'), (7, 'Amigo / Allegado'), (8, 'Otro')], verbose_name='parentesco')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='correo electrónico')),
                ('contact_number', models.CharField(blank=True, max_length=32, verbose_name='número de contacto')),
                ('email_alerts', models.BooleanField(default=False, verbose_name='alertas por correo electrónico')),
                ('whatsapp_alerts', models.BooleanField(default=False, verbose_name='alertas por WhatsApp')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='familiares residentes')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.FloatField(default=0, verbose_name='dosis')),
                ('dosage_units', models.SmallIntegerField(choices=[(1, 'mg'), (2, 'ml'), (3, 'gotas'), (1, 'mg_ml')], null=True, verbose_name='unidad de dosis')),
                ('responsible', models.TextField(blank=True, default='Ninguno', max_length=128, null=True, verbose_name='encargado de registro')),
                ('date_delivery', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de recepcion')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='presentacion')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='residente')),
            ],
            options={
                'verbose_name': 'Prescripcion',
                'verbose_name_plural': 'Prescripciones',
            },
        ),
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(null=True, verbose_name='cantidad')),
                ('delivery_units', models.SmallIntegerField(choices=[(1, 'mg'), (2, 'ml'), (3, 'gotas'), (1, 'mg_ml')], null=True, verbose_name='unidad')),
                ('date_delivery', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de recepcion')),
                ('comentarios', models.TextField(blank=True, default='Niguno', max_length=512, null=True, verbose_name='comentarios')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='presentacion')),
                ('relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.relative', verbose_name='familiar')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='residente')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.SmallIntegerField(choices=[(1, 'Ayuno'), (2, 'Mañana'), (3, 'Tarde'), (4, 'Noche')], verbose_name='hora')),
                ('dosis_diaria', models.FloatField(verbose_name='dosis diaria')),
                ('comentarios', models.TextField(blank=True, max_length=512, null=True, verbose_name='comentarios')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.prescription', verbose_name='prescripcion')),
            ],
            options={
                'verbose_name': 'Distribucion',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
    ]
