# Generated by Django 4.0.4 on 2022-11-07 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationinventory',
            name='delivery_units',
            field=models.SmallIntegerField(choices=[(1, 'mg'), (2, 'ml'), (3, 'gotas'), (1, 'mg_ml')], default=None, null=True, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.relative', verbose_name='familiar'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='kinship',
            field=models.SmallIntegerField(choices=[(1, 'Cónyuge'), (2, 'Padre / Madre'), (3, 'Hermano / Hermana'), (4, 'Hijo / Hija'), (5, 'Abuelo / Abuela'), (6, 'Familiar'), (7, 'Amigo / Allegado'), (8, 'Otro')], default=8, verbose_name='parentesco'),
        ),
    ]
