# Generated by Django 4.0.4 on 2022-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_medicationinventory_delivery_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationinventory',
            name='delivery_units',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'mg'), (2, 'ml'), (8, 'gotas'), (1, 'mg_ml'), (5, 'Tabletas'), (6, 'Cápsulas'), (7, 'Pastillas'), (8, 'Gotas'), (9, 'Jarabe'), (10, 'Inyección')], default=0, null=True, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage_units',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'mg'), (2, 'ml'), (8, 'gotas'), (1, 'mg_ml'), (5, 'Tabletas'), (6, 'Cápsulas'), (7, 'Pastillas'), (8, 'Gotas'), (9, 'Jarabe'), (10, 'Inyección')], default=0, null=True, verbose_name='unidad de dosis'),
        ),
        migrations.RemoveField(
            model_name='relative',
            name='resident',
        ),
        migrations.AddField(
            model_name='relative',
            name='resident',
            field=models.ManyToManyField(to='residents.resident', verbose_name='familiares residentes'),
        ),
    ]
