# Generated by Django 4.0.4 on 2022-11-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_alter_medicationinventory_delivery_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='resident',
        ),
        migrations.AddField(
            model_name='relative',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='familiares residentes'),
        ),
    ]
