# Generated by Django 4.0.4 on 2022-11-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_remove_relative_resident_relative_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationinventory',
            name='concepto',
            field=models.SmallIntegerField(choices=[(1, 'Entrada de inventario'), (2, 'Salida de inventario'), (3, 'Prestamo')], default=1, null=True, verbose_name='concepto'),
        ),
    ]
