# Generated by Django 4.0.4 on 2022-09-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_relative_kinship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='site',
        ),
    ]
