# Generated by Django 4.0.4 on 2022-11-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_medicationinventory_concepto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationinventory',
            old_name='concepto',
            new_name='concept',
        ),
    ]
