# Generated by Django 4.0.4 on 2022-11-18 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_delete_medicatioinventory'),
        ('residents', '0006_rename_concepto_medicationinventory_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(null=True, verbose_name='cantidad')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='presentacion')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='residente')),
            ],
        ),
    ]
