# Generated by Django 4.0.4 on 2022-09-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_presentation_measure_unit_and_more'),
        ('residents', '0007_resident_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.FloatField(verbose_name='dosificacion')),
                ('frequency_unit', models.SmallIntegerField(choices=[(1, 'horas'), (2, 'dias'), (3, 'semanas'), (4, 'meses')], verbose_name='unidad de frecuencia')),
                ('frequency', models.IntegerField(verbose_name='frecuencia')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='residente')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='residente')),
            ],
            options={
                'verbose_name': 'Prescripcion',
                'verbose_name_plural': 'Prescripciones',
            },
        ),
    ]
