# Generated by Django 4.0.4 on 2022-11-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='ammount',
        ),
        migrations.AddField(
            model_name='loan',
            name='ammount_loan',
            field=models.IntegerField(null=True, verbose_name='prestamo'),
        ),
    ]
