# Generated by Django 4.0.4 on 2022-11-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_remove_loan_ammount_loan_ammount_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_units',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'mg'), (2, 'ml'), (4, 'mg_ml'), (5, 'Tabletas'), (6, 'Cápsulas'), (7, 'Pastillas'), (8, 'Gotas'), (9, 'Jarabe'), (10, 'Inyección')], default=0, null=True, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='delivery_units',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'mg'), (2, 'ml'), (4, 'mg_ml'), (5, 'Tabletas'), (6, 'Cápsulas'), (7, 'Pastillas'), (8, 'Gotas'), (9, 'Jarabe'), (10, 'Inyección')], default=0, null=True, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage_units',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'mg'), (2, 'ml'), (4, 'mg_ml'), (5, 'Tabletas'), (6, 'Cápsulas'), (7, 'Pastillas'), (8, 'Gotas'), (9, 'Jarabe'), (10, 'Inyección')], default=0, null=True, verbose_name='unidad de dosis'),
        ),
    ]
