# Generated by Django 4.0.4 on 2022-09-06 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicatioinventory'),
        ('residents', '0008_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('date_delivery', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de recepcion')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='residente')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='residente')),
            ],
            options={
                'verbose_name': 'Prescripcion',
                'verbose_name_plural': 'Prescripciones',
            },
        ),
    ]
