# Generated by Django 4.0.4 on 2022-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_loan_loan_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='hora',
            field=models.SmallIntegerField(choices=[(1, 'Ayuno'), (2, 'Mañana'), (3, 'Tarde'), (4, 'Noche')], default=1, verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='concept',
            field=models.SmallIntegerField(choices=[(1, 'Entrada de inventario'), (2, 'Salida de inventario'), (3, 'Prestamo'), (4, 'Pago de Prestamo')], default=1, null=True, verbose_name='concepto'),
        ),
    ]
