# Generated by Django 4.0.4 on 2022-09-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_alter_prescription_options_medicationinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='site',
        ),
    ]
