# Generated by Django 4.0.4 on 2022-09-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_first_name_alter_user_identification_type'),
        ('residents', '0010_remove_resident_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site', verbose_name='sede'),
        ),
    ]
