# Generated by Django 4.0.4 on 2022-09-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_resident_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationinventory',
            name='relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.relative', verbose_name='familiar'),
        ),
    ]
