# Generated by Django 4.0.4 on 2022-09-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0012_medicationinventory_relative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationinventory',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescripcion', 'verbose_name_plural': 'Prescripciones'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
        migrations.RemoveField(
            model_name='medicationinventory',
            name='presentation',
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.prescription', verbose_name='prescripcion'),
        ),
    ]
