# Generated by Django 4.0.4 on 2022-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_alter_medicationinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.FloatField(verbose_name='dosis'),
        ),
    ]
