# Generated by Django 4.0.4 on 2022-09-09 20:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0015_alter_prescription_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=8), blank=True, null=True, size=8),
        ),
    ]
