# Generated by Django 4.0.4 on 2022-09-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0016_prescription_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='board',
        ),
    ]
