# Generated by Django 4.0.4 on 2022-09-16 07:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_delete_medicatioinventory'),
        ('residents', '0017_remove_prescription_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arreglo', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True, verbose_name='numero'), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicationinventory',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency_unit',
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.TextField(blank=True, max_length=512, null=True, verbose_name='hora de ingreso')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.prescription', verbose_name='prescripcion')),
            ],
        ),
        migrations.CreateModel(
            name='distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.SmallIntegerField(choices=[(1, 'Ayuno'), (2, 'Mañana'), (3, 'Tarde'), (4, 'Noche')], verbose_name='hora')),
                ('dosis_diaria', models.FloatField(verbose_name='dosis diaria')),
                ('comentarios', models.TextField(blank=True, max_length=512, null=True, verbose_name='comentarios')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.prescription', verbose_name='prescripcion')),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de ingreso')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('comentarios', models.TextField(blank=True, max_length=512, null=True, verbose_name='comentarios')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='presentacion')),
            ],
        ),
    ]
