# Generated by Django 4.0.4 on 2022-09-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0018_test_remove_medicationinventory_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
    ]
