# Generated by Django 4.0.4 on 2022-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0019_remove_prescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.FloatField(default=0, verbose_name='dosis'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_units',
            field=models.SmallIntegerField(choices=[(1, 'mg'), (2, 'ml'), (3, 'gotas'), (1, 'mg_ml')], null=True, verbose_name='unidad de dosis'),
        ),
    ]
