# Generated by Django 4.0.4 on 2022-09-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_delete_medicatioinventory'),
        ('residents', '0020_prescription_dosage_prescription_dosage_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='presentation',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='medicationinventory',
            old_name='quantity',
            new_name='ammount',
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='comentarios',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='comentarios'),
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='delivery_units',
            field=models.SmallIntegerField(choices=[(1, 'mg'), (2, 'ml'), (3, 'gotas'), (1, 'mg_ml')], null=True, verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='presentacion'),
        ),
        migrations.DeleteModel(
            name='delivery',
        ),
    ]
