# Generated by Django 4.0.4 on 2022-09-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_delete_medicatioinventory'),
        ('residents', '0021_remove_delivery_presentation_delete_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Distribucion', 'verbose_name_plural': 'Distribuciones'},
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='ammount',
            field=models.IntegerField(blank=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='delivery_units',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'mg'), (2, 'ml'), (3, 'gotas'), (1, 'mg_ml')], null=True, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.presentation', verbose_name='presentacion'),
        ),
        migrations.AlterField(
            model_name='medicationinventory',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.relative', verbose_name='familiar'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='familiares residentes'),
        ),
        migrations.CreateModel(
            name='EmailTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='residente')),
            ],
        ),
    ]
