# Generated by Django 4.0.4 on 2022-09-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0022_alter_distribution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='EmailTest',
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
    ]
